### ISSUE TITLE
Complete User Auth

### ISSUE THREAD

**Issue by grantpaulson6** [grantpaulson6/nomadic-nests-full-stack-project#2]
Added demo login, fixed some bugs, added splash page image.

**Comment by minucos** [comment]
Hi Grant,

First MVP looks good! In terms of your MVP checklist: 

- [x] signup, login, and logout capabilities
- [x] modal functionality
- [x] protected routes (later, for bookings)
- [x] demo login

All complete.

The only issue I would say needs some work is the height of your signup modal. Only one minor adjustment for your styling:

- [ ] adjust the signup modal so that the container is large enough to fit all inputs, including when all error messages are displayed

Just tick that off when its done, anytime before you submit your next MVP.

Nice work!

**Comment by grantpaulson6** [comment]
> Hi Grant,
> 
> First MVP looks good! In terms of your MVP checklist:
> 
> * [x]  signup, login, and logout capabilities
> * [x]  modal functionality
> * [x]  protected routes (later, for bookings)
> * [x]  demo login
> 
> All complete.
> 
> The only issue I would say needs some work is the height of your signup modal. Only one minor adjustment for your styling:
> 
> * [ ]  adjust the signup modal so that the container is large enough to fit all inputs, including when all error messages are displayed
> 
> Just tick that off when its done, anytime before you submit your next MVP.
> 
> Nice work!

I have overflow set to scroll, so you can scroll through the modal. Do you want something else?

**Comment by minucos** [comment]
Hi Grant

Spent some time this morning reviewing your project, and I think we'll just leave the scrolling as is. Airbnb's sign up page scrolls the entire page as opposed to just the form, but honestly I don't think thats worth adjusting just to be "pixel perfect".

Frankly I think the form scrolling looks cleaner than their implementation!

Issue now closed off :)
